language: ruby
bundler_args: --without development
rvm:
- 1.9.3
- 2.1.2
deploy:
  provider: rubygems
  api_key:
    secure: IiMz64fFryLhw23uEv2GlluTufOnO+PGJqeqx7aqvHZO2bThpiLxP7Dv7I9QN5u6546/BiWEPum9+mh5t8FfIVR5dKus65EzZs+gqvB4mUBKDCx7soaTRJ6dshrHrV+vEgwZyWk07HuXA/IlcTx/qNHzQXeTsCXlt66DJZDL5is=
  gem: guard-zeus
  on:
    repo: guard/guard-zeus
